### ISSUE TITLE
Update for testssh.sh 2.8

### ISSUE THREAD

**Issue by greensopinion** [MatthewVance/testssl-docker#3]
Hi, it looks like testssl.sh 2.8 was released a few days ago: https://github.com/drwetter/testssl.sh/releases

Any plans to update this docker image to support the latest release?

David

**Comment by MatthewVance** [comment]
Thanks. I missed the release. I had been checking periodically. I'd like to support the new release. I haven't looked into it yet, but I'm hoping it is an easy update to make. Thanks again.

**Comment by MatthewVance** [comment]
I've completed the update. Please let me know if you encounter any issues.

**Comment by greensopinion** [comment]
Great, thanks!

**Comment by greensopinion** [comment]
@MatthewVance running this we're seeing `Fatal error: No IPv4 address for "myhostname" available` which looks like issue #1 - any ideas?

**Comment by MatthewVance** [comment]
@greensopinion can you provide more detail? What command were you trying to run? Were you scanning an internal or external DNS name? I did a quick check and the latest version appeared to work when I scanned an Internet address. However, I got a similar error when trying to scan a FQDN on my LAN. I believe this was because the DNS config of my Docker instance wasn't using my internal DNS server.

**Comment by greensopinion** [comment]
@MatthewVance we're using the following Dockerfile:

````
FROM mvance/testssl:2.8rc3


RUN apt-get update && \
    apt-get install -y \
        netcat && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD testssl-wait.sh /testssl-wait.sh

ENTRYPOINT ["/testssl-wait.sh"]
````

the `testssl-wait.sh` looks like this:

````
#!/bin/bash

set -e

if [ $# -ne 2 ]
  then
    echo "usage: testsssl-wait.sh <hostname> <port>\n (got $# arguments: $*)" && exit -1
fi

TESTSSL_HOSTNAME=$1
TESTSSL_PORT=$2

echo -e "Waiting for availability of $TESTSSL_HOSTNAME:$TESTSSL_PORT"
while ! nc -w 1 -z $TESTSSL_HOSTNAME $TESTSSL_PORT; do
  sleep 2;
  echo "."
done
echo "$TESTSSL_HOSTNAME:$TESTSSL_PORT available"

testssl.sh --color 0  $TESTSSL_HOSTNAME:$TESTSSL_PORT | tee testssl.out

if $(grep -i "Fatal error" testssl.out); then
    grep -i "Fatal error" testssl.out && exit -1
fi

TESTSSL_RESULT=$(grep -i "(NOT ok)" testssl.out | wc -l)
if [ "$TESTSSL_RESULT" -ne "0" ]; then
    echo "Failed with $TESTSSL_RESULT violations:" && grep -i "(NOT ok)" testssl.out && exit -1
fi
````

The Docker container is brought up in a `docker-compose` environment with the other container being an HTTP webserver (Tomcat actually).  Here's the `docker-compose.yml`:

````
platform:
  image: docker.van.tasktop.com/thewebserver
  ports:
   - 8443
testssl:
  container_name: testssl
  image: docker.van.tasktop.com/testssl
  links:
   - platform
  command: platform 8443
````

**Comment by MatthewVance** [comment]
Interesting. I'm not sure what it would be, if not a local DNS issue given what happened when I tested it. I ran it with with something more like `sudo docker run -t --rm mvance/testssl:2.8rc3 --protocols example.com`. You might also look into the other Docker repo for this at https://github.com/jumanjihouse/docker-testssl to see if it works. You may need to revise the code to use the latest release.

**Comment by greensopinion** [comment]
in case anyone else is interested, we solved this problem by declaring the docker-compose version number as 2.1 at the top of the docker-compose.yml:

```
version: '2.1'

services:
  platform:
    image: docker.van.tasktop.com/thewebserver
    ports:
     - 8443
  testssl:
    container_name: testssl
    image: docker.van.tasktop.com/testssl
    links:
     - platform
    command: platform 8443
```
